[versions]
agp = "8.13.0"
kotlin = "2.2.20"
compose-multiplatform = "1.10.0-alpha02"
navigation-compose = "2.9.1"
core-ktx = "1.15.0"
material-icons = "1.7.7"
kotlin-serialization = "1.9.0"
snizzors = "1.0.0"
datetime-wheel-picker = "1.1.0-alpha05-compose1.9"
kotlinx-datetime = "0.7.1-0.6.x-compat"

[libraries]
yalla-design = { module = "uz.yalla:design", version = "1.1.0" }
yalla-resources = { module = "uz.yalla:resources", version = "1.4.5" }
navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "material-icons" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin-serialization" }
snizzors = { module = "com.infiniteretry.snizzors:snizzors", version.ref = "snizzors" }
datetime-wheel-picker = { module = "io.github.darkokoa:datetime-wheel-picker", version.ref = "datetime-wheel-picker" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
