[versions]
agp = "8.13.0"
kotlin = "2.2.20"
compose-multiplatform = "1.10.0-alpha02"
navigation-compose = "2.9.1"
core-ktx = "1.15.0"
material-icons = "1.7.7"

[libraries]
yalla-design = { module = "uz.yalla:design", version = "1.0.0" }
navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "material-icons" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
